name: Build and Publish Front End Framework Website
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions: write-all
jobs:
  Angular-Build-Action:
    name: Angular-Build-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js 22.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci || npm install --force

      - name: Clean Previous Builds
        run: rm -rf dist

      - name: Run Angular Build
        run: npm run build -- --configuration production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: ""
          
      - name: Publish Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          contextName: docker/Dockerfile
          tag: |
            latest
            ${{ github.sha }}
